### ISSUE TITLE
Execute issue with windows

### ISSUE THREAD

**Issue by shivapoudel** [robotlolita/fuck-you#20]
In windows we have to do `fuck you firefox.exe`. Can't we make compatible just by ignoring `*.exe` suffix. Most of the Windows Apps and programs are with `*.exe` so please kill the process if we run this too `fuck you firefox` :P

**Comment by danyshaanan** [comment]
You could probably give it a try by changing

```js
return new RegExp('^' + escape(pattern) + '$', 'i');
```

with something like

```js
return new RegExp('^' + escape(pattern) + '(\.exe)?$', 'i');
```

(Not using windows, can't check).

**Comment by shivapoudel** [comment]
Using `return new RegExp('^' + escape(pattern) + '(\.exe)?$', 'i');` works great for Windows. @robotlolita could you please update the version with this change adapted for Windows Users.

**Comment by danyshaanan** [comment]
@shivapoudel You should probably create a pull request.

**Comment by robotlolita** [comment]
`a.exe` and `a` are two different processes in most operating systems, I'm not sure about Windows (not really familiar), but Windows also differentiates between processes that have different extensions (e.g. `a.cmd` and `a.exe` would both match that regular expression, even if Windows can't run processes that have no extension).

That said, you should be able to use `fuck you firefox*` on Windows to match all processes starting with `firefox`.

I'm not really sure what's the best way of making this simpler for Windows. I'd like to err on the side of not matching processes you're not interested in by default. A regular expression that optionally matches `$1.exe` only on Windows could work iff Windows can't execute processes that are named just `$1` (otherwise you'd be matching more processes than it should).

**Comment by shivapoudel** [comment]
If `a.cmd` then that is run by the `cmd.exe` so all the Windows depends upon `*.exe`. And in most of the cases I have not found any processes running `$1` all are `$1.exe` in Windows.
